Repository femueller/python-n26, pull requests merged in 2020-10, with the labels that each got.

#91 dependency updates
  Pipfile
  Pipfile.lock
Labels: dependencies

#90 Bank transfer order functionality added
  n26/api.py
  n26/cli.py
  requirements.txt
Labels: enhancement, hacktoberfest

#92 Feature/logout
  n26/api.py
  n26/cli.py
Labels: enhancement

#93 dont do auth on logout (doh)
  n26/cli.py
Labels: bug
